SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Client] (
		[ClientId]       [int] IDENTITY(1, 1) NOT NULL,
		[ClientName]     [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK34]
		PRIMARY KEY
		NONCLUSTERED
		([ClientId])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Client] SET (LOCK_ESCALATION = TABLE)
GO
