SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Scope] (
		[ScopeId]     [int] IDENTITY(1, 1) NOT NULL,
		[Scope]       [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK3]
		PRIMARY KEY
		NONCLUSTERED
		([ScopeId])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Scope] SET (LOCK_ESCALATION = TABLE)
GO
