SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ShellTheme] (
		[ShellThemeId]     [int] IDENTITY(1, 1) NOT NULL,
		[ShellTheme]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK38]
		PRIMARY KEY
		NONCLUSTERED
		([ShellThemeId])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ShellTheme] SET (LOCK_ESCALATION = TABLE)
GO
