SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[City] (
		[CityId]       [int] IDENTITY(1, 1) NOT NULL,
		[CityName]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [Pk_City]
		PRIMARY KEY
		CLUSTERED
		([CityId])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[City] SET (LOCK_ESCALATION = TABLE)
GO
