SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Status] (
		[StatusId]     [int] IDENTITY(1, 1) NOT NULL,
		[Status]       [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK16]
		PRIMARY KEY
		NONCLUSTERED
		([StatusId])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Status] SET (LOCK_ESCALATION = TABLE)
GO
